# Terraform Beginner Bootcamp 2023 - Week 0

- [Semantic versioning :mage:](#semantic-versioning--mage-)
- [Install the terraform CLI](#install-the-terraform-cli)
  * [Considerations with the Terraform CLI changes](#considerations-with-the-terraform-cli-changes)
  * [Considerations for Linux Distributions](#considerations-for-linux-distributions)
  * [Refactoring into bash scripts](#refactoring-into-bash-scripts)
    + [Shebang considerations](#shebang-considerations)
    + [Execution Considerations](#execution-considerations)
    + [Linux Permissions Considerations](#linux-permissions-considerations)
  * [Github lifecycle (before, init, command)](#github-lifecycle--before--init--command-)
  * [Working with environment variables](#working-with-environment-variables)
    + [env command](#env-command)
    + [Setting and unsetting env vars](#setting-and-unsetting-env-vars)
    + [Printing env vars](#printing-env-vars)
    + [Scoping of env vars](#scoping-of-env-vars)
    + [Persisting env vars in Gitpod](#persisting-env-vars-in-gitpod)
  * [AWS CLI installation](#aws-cli-installation)
- [Terraform Basics](#terraform-basics)
  * [Terraform Registry](#terraform-registry)
  * [Terraform Console](#terraform-console)
    + [Terraform init](#terraform-init)
    + [Terraform Plan](#terraform-plan)
    + [Terraform Apply](#terraform-apply)
    + [Terraform Destroy](#terraform-destroy)
    + [Terraform Lock Files](#terraform-lock-files)
    + [Terraform Directory](#terraform-directory)
- [Issues with Terrform Cloud Login and Gitpod Workspace](#issues-with-terrform-cloud-login-and-gitpod-workspace)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>
